### ISSUE TITLE
At 'Stop', ASReview doesn't offer to export results.

### ISSUE THREAD

**Issue by GerbrichFerdinands** [msdslab/automated-systematic-review#136]
I feel like the 'Export' and 'Stop' options aren't in optimal form.

When I want to stop reviewing, I expected the software to offer me the option to export. However, that is not the case:

```
----------------------------------


| 0.07% read | 2 since last inclusion | 25.00% included | total papers: 4/5782 |

? Include or Exclude?  Stop
? Are you sure you want to stop?  Yes

Closing down the automated systematic review.
```

If I want to export my results & quit, I first have to select the ` Export` button, and then after exporting I have to select ` Stop`. This might be a bit inconvenient.

**Comment by J535D165** [comment]
Thanks, good point. This is confusing. Shall we remove the 'Export' button? The stop button is oke I think.

**Comment by qubixes** [comment]
It used to be that way. I changed it because you don't shouldn't need to export every time you need a break from reviewing. Maybe it is more logical to put a stop option after exporting the results? Also, perhaps it should be called "Quit" instead, because you're not actually stopping the review (just temporarily).

**Comment by GerbrichFerdinands** [comment]
I guess most users (at least I) will intuitively think that if they don't export before having a break,  their data will be lost. 

How about first "Quit", followed by a question if you want to export?

**Comment by J535D165** [comment]
Agree. Let's implement.

**Comment by qubixes** [comment]
How about renaming it to "Save & Quit" then? That should solve that particular issue then, no? 

I think in the end, what we actually need is a proper main menu. So instead of Export/Stop, we'd have one option to return to the main menu. And in the main menu there would be options to quit, restart the review, export, add more initial papers, etc.

**Comment by J535D165** [comment]
True. Please keep in mind that we are only making minor changes to the CLI from now on. No big changes please :) I will attach the UX people to this issue.
