### ISSUE TITLE
Loading embedding matrix fails

### ISSUE THREAD

**Issue by J535D165** [msdslab/automated-systematic-review#27]
The following code takes forever on my MBP (i7, 16GB RAM). 

``` python
In [1]: import asr                                                                                                 

In [2]: %timeit asr.load_embedding("/Users/jonathan/asr_data/fasttext.cc.en.300.vec")                              
Reading 2000000 vectors with 300 dimensions.
```

Can someone verify this? Possible bug in #9?

**Comment by qubixes** [comment]
At least on my machine it takes too much RAM. It is probably because putting stuff in a queue makes too many copies (2,3?) of the data. So, if you use sampling, you won't encounter it because it doesn't store all the data. Suggestion for a solution?
- Get *another* process to do the file reading + main process collects the data.
- Managers for data collection?

**Comment by qubixes** [comment]
Tried both, but using managers was way too slow (and didn't solve the problem). See pull request.

**Comment by qubixes** [comment]
Close?

**Comment by J535D165** [comment]
You're right, thanks.
